#%RAML 1.0
title: salesforce-opportunities-api

/opportunities:
  /{id}:
    get:
      responses:
        200:
          body:
            application/json:
              type: any

/gettime:
  get:
    responses:
      200:
        body:
          application/json:
            